default:
  golem_name: GemBank
  golem_version: 0.1.0
  app_title: GemBank Seed Management
  db_path: data/breeding_db.sqlite

production:
  db_path: /var/lib/gembank/breeding_db.sqlite

dev:
  db_path: data/breeding_db.sqlite
